#include "vestra/lex/token.hpp"

#include <string_view>
#include <unordered_map>

namespace vestra::lex {

std::string_view spelling(TokenKind k) noexcept {
    switch (k) {
    // bookkeeping
    case TokenKind::Eof:
        return "<eof>";
    case TokenKind::Error:
        return "<error>";
    case TokenKind::Newline:
        return "<newline>";
    // literals
    case TokenKind::IntLit:
        return "integer literal";
    case TokenKind::FloatLit:
        return "float literal";
    case TokenKind::StringLit:
        return "string literal";
    case TokenKind::ByteStringLit:
        return "byte string literal";
    case TokenKind::CharLit:
        return "character literal";
    case TokenKind::Identifier:
        return "identifier";
    // punctuation
    case TokenKind::LParen:
        return "(";
    case TokenKind::RParen:
        return ")";
    case TokenKind::LBrace:
        return "{";
    case TokenKind::RBrace:
        return "}";
    case TokenKind::LBracket:
        return "[";
    case TokenKind::RBracket:
        return "]";
    case TokenKind::Comma:
        return ",";
    case TokenKind::Semicolon:
        return ";";
    case TokenKind::Colon:
        return ":";
    case TokenKind::Dot:
        return ".";
    case TokenKind::DotDot:
        return "..";
    case TokenKind::DotDotLt:
        return "..<";
    case TokenKind::Arrow:
        return "->";
    case TokenKind::FatArrow:
        return "=>";
    case TokenKind::At:
        return "@";
    case TokenKind::Question:
        return "?";
    case TokenKind::Underscore:
        return "_";
    // operators
    case TokenKind::Plus:
        return "+";
    case TokenKind::Minus:
        return "-";
    case TokenKind::Star:
        return "*";
    case TokenKind::Slash:
        return "/";
    case TokenKind::Percent:
        return "%";
    case TokenKind::AmpPlus:
        return "&+";
    case TokenKind::AmpMinus:
        return "&-";
    case TokenKind::AmpStar:
        return "&*";
    case TokenKind::Amp:
        return "&";
    case TokenKind::Pipe:
        return "|";
    case TokenKind::Caret:
        return "^";
    case TokenKind::Tilde:
        return "~";
    case TokenKind::Bang:
        return "!";
    case TokenKind::ShiftL:
        return "<<";
    case TokenKind::ShiftR:
        return ">>";
    case TokenKind::Assign:
        return "=";
    case TokenKind::PlusEq:
        return "+=";
    case TokenKind::MinusEq:
        return "-=";
    case TokenKind::StarEq:
        return "*=";
    case TokenKind::SlashEq:
        return "/=";
    case TokenKind::PercentEq:
        return "%=";
    case TokenKind::AmpEq:
        return "&=";
    case TokenKind::PipeEq:
        return "|=";
    case TokenKind::CaretEq:
        return "^=";
    case TokenKind::ShiftLEq:
        return "<<=";
    case TokenKind::ShiftREq:
        return ">>=";
    case TokenKind::EqEq:
        return "==";
    case TokenKind::BangEq:
        return "!=";
    case TokenKind::Lt:
        return "<";
    case TokenKind::Gt:
        return ">";
    case TokenKind::LtEq:
        return "<=";
    case TokenKind::GtEq:
        return ">=";
    case TokenKind::AmpAmp:
        return "&&";
    case TokenKind::PipePipe:
        return "||";
    case TokenKind::QuestionQuestion:
        return "??";
    // keywords
    case TokenKind::KwModule:
        return "module";
    case TokenKind::KwImport:
        return "import";
    case TokenKind::KwFunc:
        return "func";
    case TokenKind::KwStruct:
        return "struct";
    case TokenKind::KwEnum:
        return "enum";
    case TokenKind::KwProtocol:
        return "protocol";
    case TokenKind::KwExtension:
        return "extension";
    case TokenKind::KwOpaque:
        return "opaque";
    case TokenKind::KwType:
        return "type";
    case TokenKind::KwEmbed:
        return "embed";
    case TokenKind::KwDeinit:
        return "deinit";
    case TokenKind::KwLet:
        return "let";
    case TokenKind::KwVar:
        return "var";
    case TokenKind::KwConst:
        return "const";
    case TokenKind::KwStatic:
        return "static";
    case TokenKind::KwReturn:
        return "return";
    case TokenKind::KwIf:
        return "if";
    case TokenKind::KwElse:
        return "else";
    case TokenKind::KwMatch:
        return "match";
    case TokenKind::KwCase:
        return "case";
    case TokenKind::KwDefault:
        return "default";
    case TokenKind::KwFor:
        return "for";
    case TokenKind::KwIn:
        return "in";
    case TokenKind::KwWhile:
        return "while";
    case TokenKind::KwBreak:
        return "break";
    case TokenKind::KwContinue:
        return "continue";
    case TokenKind::KwWhere:
        return "where";
    case TokenKind::KwDo:
        return "do";
    case TokenKind::KwCatch:
        return "catch";
    case TokenKind::KwThrow:
        return "throw";
    case TokenKind::KwThrows:
        return "throws";
    case TokenKind::KwWith:
        return "with";
    case TokenKind::KwUsing:
        return "using";
    case TokenKind::KwAsync:
        return "async";
    case TokenKind::KwAwait:
        return "await";
    case TokenKind::KwSpawn:
        return "spawn";
    case TokenKind::KwSelect:
        return "select";
    case TokenKind::KwOn:
        return "on";
    case TokenKind::KwComptime:
        return "comptime";
    case TokenKind::KwQuote:
        return "quote";
    case TokenKind::KwCopy:
        return "copy";
    case TokenKind::KwRead:
        return "read";
    case TokenKind::KwInout:
        return "inout";
    case TokenKind::KwSink:
        return "sink";
    case TokenKind::KwNonescaping:
        return "nonescaping";
    case TokenKind::KwSome:
        return "some";
    case TokenKind::KwDyn:
        return "dyn";
    case TokenKind::KwLinear:
        return "linear";
    case TokenKind::KwTry:
        return "try";
    case TokenKind::KwTryQuestion:
        return "try?";
    case TokenKind::KwTryBang:
        return "try!";
    case TokenKind::KwAs:
        return "as";
    case TokenKind::KwAsQuestion:
        return "as?";
    case TokenKind::KwDerive:
        return "derive";
    case TokenKind::KwTrue:
        return "true";
    case TokenKind::KwFalse:
        return "false";
    case TokenKind::KwSelfLower:
        return "self";
    case TokenKind::KwSelfUpper:
        return "Self";
    case TokenKind::KwPrivate:
        return "private";
    case TokenKind::KwInternal:
        return "internal";
    case TokenKind::KwPackage:
        return "package";
    case TokenKind::KwPublic:
        return "public";
    }
    return "<unknown>";
}

TokenKind keyword_or_identifier(std::string_view lexeme) noexcept {
    // Static linear-probed hash table; the §17.1 keyword set is small and fixed,
    // so a once-initialized map is the right thing here.
    static const std::unordered_map<std::string_view, TokenKind> kw{
        {"module", TokenKind::KwModule},
        {"import", TokenKind::KwImport},
        {"func", TokenKind::KwFunc},
        {"struct", TokenKind::KwStruct},
        {"enum", TokenKind::KwEnum},
        {"protocol", TokenKind::KwProtocol},
        {"extension", TokenKind::KwExtension},
        {"opaque", TokenKind::KwOpaque},
        {"type", TokenKind::KwType},
        {"embed", TokenKind::KwEmbed},
        {"deinit", TokenKind::KwDeinit},
        {"let", TokenKind::KwLet},
        {"var", TokenKind::KwVar},
        {"const", TokenKind::KwConst},
        {"static", TokenKind::KwStatic},
        {"return", TokenKind::KwReturn},
        {"if", TokenKind::KwIf},
        {"else", TokenKind::KwElse},
        {"match", TokenKind::KwMatch},
        {"case", TokenKind::KwCase},
        {"default", TokenKind::KwDefault},
        {"for", TokenKind::KwFor},
        {"in", TokenKind::KwIn},
        {"while", TokenKind::KwWhile},
        {"break", TokenKind::KwBreak},
        {"continue", TokenKind::KwContinue},
        {"where", TokenKind::KwWhere},
        {"do", TokenKind::KwDo},
        {"catch", TokenKind::KwCatch},
        {"throw", TokenKind::KwThrow},
        {"throws", TokenKind::KwThrows},
        {"with", TokenKind::KwWith},
        {"using", TokenKind::KwUsing},
        {"async", TokenKind::KwAsync},
        {"await", TokenKind::KwAwait},
        {"spawn", TokenKind::KwSpawn},
        {"select", TokenKind::KwSelect},
        {"on", TokenKind::KwOn},
        {"comptime", TokenKind::KwComptime},
        {"quote", TokenKind::KwQuote},
        {"copy", TokenKind::KwCopy},
        {"read", TokenKind::KwRead},
        {"inout", TokenKind::KwInout},
        {"sink", TokenKind::KwSink},
        {"nonescaping", TokenKind::KwNonescaping},
        {"some", TokenKind::KwSome},
        {"dyn", TokenKind::KwDyn},
        {"linear", TokenKind::KwLinear},
        {"try", TokenKind::KwTry},
        {"as", TokenKind::KwAs},
        {"derive", TokenKind::KwDerive},
        {"true", TokenKind::KwTrue},
        {"false", TokenKind::KwFalse},
        {"self", TokenKind::KwSelfLower},
        {"Self", TokenKind::KwSelfUpper},
        {"private", TokenKind::KwPrivate},
        {"internal", TokenKind::KwInternal},
        {"package", TokenKind::KwPackage},
        {"public", TokenKind::KwPublic},
    };

    auto it = kw.find(lexeme);
    return it == kw.end() ? TokenKind::Identifier : it->second;
}

}  // namespace vestra::lex
