#include "vestra/codegen/cpp_emitter.hpp"

#include <format>
#include <ostream>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_map>

namespace vestra::codegen {

namespace {

void write_indent(std::ostream& os, int indent) {
    for (int i = 0; i < indent; ++i) {
        os << "    ";
    }
}

// Map Vestra primitive names to C++23 equivalents.
const std::unordered_map<std::string, std::string>& primitive_map() {
    static const std::unordered_map<std::string, std::string> m = {
        {"Int8", "std::int8_t"},
        {"Int16", "std::int16_t"},
        {"Int32", "std::int32_t"},
        {"Int64", "std::int64_t"},
        {"UInt8", "std::uint8_t"},
        {"UInt16", "std::uint16_t"},
        {"UInt32", "std::uint32_t"},
        {"UInt64", "std::uint64_t"},
        {"Int", "std::intptr_t"},
        {"UInt", "std::uintptr_t"},
        {"Float32", "float"},
        {"Float64", "double"},
        {"Bool", "bool"},
        {"Char", "char32_t"},
        {"Unit", "void"},
        {"String", "std::string"},
        {"Str", "std::string_view"},
        {"StrConst", "std::string_view"},
    };
    return m;
}

}  // namespace

// ----------------------------------------------------------------------------

EmittedUnit CppEmitter::emit(const ast::CompilationUnit& unit, std::string_view output_basename) {
    std::ostringstream hdr;
    std::ostringstream src;

    auto guard = std::string{output_basename};
    for (auto& c : guard) {
        c = (std::isalnum(static_cast<unsigned char>(c)) != 0)
                ? static_cast<char>(std::toupper(static_cast<unsigned char>(c)))
                : '_';
    }

    hdr << "// Generated by vestra-transpiler. Do not edit.\n";
    hdr << "#pragma once\n\n";
    hdr << "#include <cstdint>\n";
    hdr << "#include <string>\n";
    hdr << "#include <string_view>\n";
    hdr << "#include <variant>\n";
    hdr << "#include <vector>\n\n";

    if (unit.module) {
        // Vestra module path → C++ nested namespace.
        hdr << "namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                hdr << "::";
            }
            hdr << unit.module->path[i];
        }
        hdr << " {\n\n";
    }

    src << "// Generated by vestra-transpiler. Do not edit.\n";
    src << "#include \"" << output_basename << ".hpp\"\n\n";

    if (unit.module) {
        src << "namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                src << "::";
            }
            src << unit.module->path[i];
        }
        src << " {\n\n";
    }

    for (const auto& d : unit.decls) {
        emit_decl(hdr, src, *d);
    }

    if (unit.module) {
        hdr << "\n}  // namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                hdr << "::";
            }
            hdr << unit.module->path[i];
        }
        hdr << "\n";
        src << "\n}  // namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                src << "::";
            }
            src << unit.module->path[i];
        }
        src << "\n";
    }

    return {hdr.str(), src.str()};
}

// ----------------------------------------------------------------------------

void CppEmitter::unsupported(std::ostream& os, std::string_view what, diag::SourceRange r) {
    reporter_->report(
        diag::Diagnostic::warning(std::format("codegen does not yet support: {}", what)).at(r));
    os << "/* unsupported: " << what << " */";
}

const char* CppEmitter::binop_text(ast::BinaryOp op) {
    switch (op) {
    case ast::BinaryOp::Add:
        return "+";
    case ast::BinaryOp::Sub:
        return "-";
    case ast::BinaryOp::Mul:
        return "*";
    case ast::BinaryOp::Div:
        return "/";
    case ast::BinaryOp::Mod:
        return "%";
    case ast::BinaryOp::Shl:
        return "<<";
    case ast::BinaryOp::Shr:
        return ">>";
    case ast::BinaryOp::BitAnd:
        return "&";
    case ast::BinaryOp::BitOr:
        return "|";
    case ast::BinaryOp::BitXor:
        return "^";
    case ast::BinaryOp::Eq:
        return "==";
    case ast::BinaryOp::Ne:
        return "!=";
    case ast::BinaryOp::Lt:
        return "<";
    case ast::BinaryOp::Le:
        return "<=";
    case ast::BinaryOp::Gt:
        return ">";
    case ast::BinaryOp::Ge:
        return ">=";
    case ast::BinaryOp::And:
        return "&&";
    case ast::BinaryOp::Or:
        return "||";
    case ast::BinaryOp::WrappingAdd:
        return "+";  // C++ on unsigned wraps; signed UB — TODO
    case ast::BinaryOp::WrappingSub:
        return "-";
    case ast::BinaryOp::WrappingMul:
        return "*";
    default:
        return "/*?op*/";
    }
}

const char* CppEmitter::unop_text(ast::UnaryOp op) {
    switch (op) {
    case ast::UnaryOp::Neg:
        return "-";
    case ast::UnaryOp::Not:
        return "!";
    case ast::UnaryOp::BitNot:
        return "~";
    }
    return "?";
}

// ----------------------------------------------------------------------------

void CppEmitter::emit_decl(std::ostream& hdr, std::ostream& src, const ast::Decl& d) {
    switch (d.kind) {
    case ast::NodeKind::Func:
        emit_func(hdr, src, static_cast<const ast::FuncDecl&>(d));
        break;
    case ast::NodeKind::Struct:
        emit_struct(hdr, static_cast<const ast::StructDecl&>(d));
        break;
    case ast::NodeKind::Enum:
        emit_enum(hdr, static_cast<const ast::EnumDecl&>(d));
        break;
    case ast::NodeKind::Const: {
        const auto& c = static_cast<const ast::ConstDecl&>(d);
        hdr << "inline constexpr ";
        if (c.type) {
            emit_type(hdr, *c.type);
        } else {
            hdr << "auto";
        }
        hdr << " " << c.name << " = ";
        if (c.value) {
            emit_expr(hdr, *c.value);
        }
        hdr << ";\n";
        break;
    }
    case ast::NodeKind::Opaque: {
        const auto& o = static_cast<const ast::OpaqueDecl&>(d);
        hdr << "// opaque type " << o.name << "\n";
        hdr << "enum class " << o.name << " : ";
        emit_type(hdr, *o.underlying);
        hdr << " {};\n";
        break;
    }
    default:
        unsupported(hdr, std::format("top-level decl kind {}", static_cast<int>(d.kind)), d.range);
        hdr << "\n";
        break;
    }
}

void CppEmitter::emit_func(std::ostream& hdr, std::ostream& src, const ast::FuncDecl& f) {
    auto emit_signature = [&](std::ostream& os) {
        if (f.result) {
            emit_type(os, *f.result);
        } else {
            os << "void";
        }
        os << " " << f.name << "(";
        for (std::size_t i = 0; i < f.params.size(); ++i) {
            if (i != 0) {
                os << ", ";
            }
            const auto& p = f.params[i];
            // Mode mapping (very rough first pass — §5 ownership is unresolved):
            //   read  → const T&
            //   inout → T&
            //   sink  → T&&
            switch (p.mode) {
            case ast::ParamMode::Read:
                os << "const ";
                if (p.type) {
                    emit_type(os, *p.type);
                }
                os << "& " << p.name;
                break;
            case ast::ParamMode::Inout:
                if (p.type) {
                    emit_type(os, *p.type);
                }
                os << "& " << p.name;
                break;
            case ast::ParamMode::Sink:
                if (p.type) {
                    emit_type(os, *p.type);
                }
                os << "&& " << p.name;
                break;
            }
        }
        os << ")";
    };

    hdr << "[[nodiscard]] ";
    emit_signature(hdr);
    hdr << ";\n";

    if (!f.body) {
        return;
    }

    emit_signature(src);
    src << " {\n";
    if (f.body->kind == ast::NodeKind::BlockExpr) {
        const auto& blk = static_cast<const ast::BlockExpr&>(*f.body);
        for (const auto& s : blk.stmts) {
            emit_stmt(src, *s, 1);
        }
    } else {
        unsupported(src, "non-block function body", f.body->range);
    }
    src << "}\n\n";
}

void CppEmitter::emit_struct(std::ostream& hdr, const ast::StructDecl& s) {
    hdr << "struct " << s.name << " {\n";
    for (const auto& f : s.fields) {
        write_indent(hdr, 1);
        if (f.type) {
            emit_type(hdr, *f.type);
        }
        hdr << " " << f.name << "{};\n";
    }
    hdr << "};\n\n";
}

void CppEmitter::emit_enum(std::ostream& hdr, const ast::EnumDecl& e) {
    // A Vestra enum with payloads maps cleanly to std::variant; bare enums to
    // a C++ enum class. We detect "all bare" cheaply.
    bool all_bare = true;
    for (const auto& c : e.cases) {
        if (!c.payload.empty()) {
            all_bare = false;
            break;
        }
    }
    if (all_bare) {
        hdr << "enum class " << e.name << " {\n";
        for (const auto& c : e.cases) {
            write_indent(hdr, 1);
            hdr << c.name << ",\n";
        }
        hdr << "};\n\n";
        return;
    }
    // Sum type — emit a struct-of-variant. TODO: tighter sum-type lowering.
    hdr << "struct " << e.name << " {\n";
    for (const auto& c : e.cases) {
        write_indent(hdr, 1);
        hdr << "struct " << c.name << "_t {";
        for (std::size_t i = 0; i < c.payload.size(); ++i) {
            if (i != 0) {
                hdr << " ";
            }
            if (c.payload[i].second) {
                emit_type(hdr, *c.payload[i].second);
            }
            hdr << " " << (c.payload[i].first.empty() ? std::format("_{}", i) : c.payload[i].first)
                << "{}; ";
        }
        hdr << "};\n";
    }
    write_indent(hdr, 1);
    hdr << "std::variant<";
    for (std::size_t i = 0; i < e.cases.size(); ++i) {
        if (i != 0) {
            hdr << ", ";
        }
        hdr << e.cases[i].name << "_t";
    }
    hdr << "> value{};\n";
    hdr << "};\n\n";
}

void CppEmitter::emit_block(std::ostream& os, const ast::BlockExpr& b, int indent) {
    os << "{\n";
    for (const auto& s : b.stmts) {
        emit_stmt(os, *s, indent + 1);
    }
    write_indent(os, indent);
    os << "}";
}

void CppEmitter::emit_stmt(std::ostream& os, const ast::Stmt& s, int indent) {
    write_indent(os, indent);
    switch (s.kind) {
    case ast::NodeKind::LetStmt: {
        const auto& l = static_cast<const ast::LetStmt&>(s);
        if (l.type) {
            os << "const ";
            emit_type(os, *l.type);
            os << " ";
        } else {
            os << "const auto ";
        }
        if (l.pattern && l.pattern->kind == ast::NodeKind::IdentPat) {
            os << static_cast<const ast::IdentPat&>(*l.pattern).name;
        } else if (l.pattern && l.pattern->kind == ast::NodeKind::BindPat) {
            os << static_cast<const ast::BindPat&>(*l.pattern).name;
        } else {
            os << "_bind";
        }
        os << " = ";
        if (l.value) {
            emit_expr(os, *l.value);
        }
        os << ";\n";
        break;
    }
    case ast::NodeKind::VarStmt: {
        const auto& v = static_cast<const ast::VarStmt&>(s);
        if (v.type) {
            emit_type(os, *v.type);
            os << " ";
        } else {
            os << "auto ";
        }
        if (v.pattern && v.pattern->kind == ast::NodeKind::IdentPat) {
            os << static_cast<const ast::IdentPat&>(*v.pattern).name;
        } else if (v.pattern && v.pattern->kind == ast::NodeKind::BindPat) {
            os << static_cast<const ast::BindPat&>(*v.pattern).name;
        } else {
            os << "_bind";
        }
        os << " = ";
        if (v.value) {
            emit_expr(os, *v.value);
        }
        os << ";\n";
        break;
    }
    case ast::NodeKind::ExprStmt:
        emit_expr(os, *static_cast<const ast::ExprStmt&>(s).expr);
        os << ";\n";
        break;
    case ast::NodeKind::ReturnStmt: {
        const auto& r = static_cast<const ast::ReturnStmt&>(s);
        os << "return";
        if (r.value) {
            os << " ";
            emit_expr(os, *r.value);
        }
        os << ";\n";
        break;
    }
    case ast::NodeKind::BreakStmt:
        os << "break;\n";
        break;
    case ast::NodeKind::ContinueStmt:
        os << "continue;\n";
        break;
    case ast::NodeKind::AssignStmt: {
        const auto& a = static_cast<const ast::AssignStmt&>(s);
        emit_expr(os, *a.target);
        switch (a.op) {
        case ast::AssignOp::Assign:
            os << " = ";
            break;
        case ast::AssignOp::AddAssign:
            os << " += ";
            break;
        case ast::AssignOp::SubAssign:
            os << " -= ";
            break;
        case ast::AssignOp::MulAssign:
            os << " *= ";
            break;
        case ast::AssignOp::DivAssign:
            os << " /= ";
            break;
        case ast::AssignOp::ModAssign:
            os << " %= ";
            break;
        case ast::AssignOp::BitAndAssign:
            os << " &= ";
            break;
        case ast::AssignOp::BitOrAssign:
            os << " |= ";
            break;
        case ast::AssignOp::BitXorAssign:
            os << " ^= ";
            break;
        case ast::AssignOp::ShlAssign:
            os << " <<= ";
            break;
        case ast::AssignOp::ShrAssign:
            os << " >>= ";
            break;
        }
        emit_expr(os, *a.value);
        os << ";\n";
        break;
    }
    case ast::NodeKind::WhileStmt: {
        const auto& w = static_cast<const ast::WhileStmt&>(s);
        os << "while (";
        emit_expr(os, *w.cond);
        os << ") ";
        if (w.body && w.body->kind == ast::NodeKind::BlockExpr) {
            emit_block(os, static_cast<const ast::BlockExpr&>(*w.body), indent);
            os << "\n";
        } else {
            os << "{}\n";
        }
        break;
    }
    case ast::NodeKind::ForStmt: {
        const auto& f = static_cast<const ast::ForStmt&>(s);
        os << "for (const auto& ";
        if (f.pattern && f.pattern->kind == ast::NodeKind::IdentPat) {
            os << static_cast<const ast::IdentPat&>(*f.pattern).name;
        } else if (f.pattern && f.pattern->kind == ast::NodeKind::BindPat) {
            os << static_cast<const ast::BindPat&>(*f.pattern).name;
        } else {
            os << "_it";
        }
        os << " : ";
        emit_expr(os, *f.iter);
        os << ") ";
        if (f.body && f.body->kind == ast::NodeKind::BlockExpr) {
            emit_block(os, static_cast<const ast::BlockExpr&>(*f.body), indent);
            os << "\n";
        } else {
            os << "{}\n";
        }
        break;
    }
    default:
        unsupported(os, "stmt", s.range);
        os << "\n";
        break;
    }
}

void CppEmitter::emit_expr(std::ostream& os, const ast::Expr& e) {
    switch (e.kind) {
    case ast::NodeKind::IntLit:
        os << static_cast<const ast::IntLit&>(e).text;
        break;
    case ast::NodeKind::FloatLit:
        os << static_cast<const ast::FloatLit&>(e).text;
        break;
    case ast::NodeKind::StringLit:
        os << "std::string_view(\"" << static_cast<const ast::StringLit&>(e).text << "\")";
        break;
    case ast::NodeKind::CharLit:
        os << "U'" << static_cast<const ast::CharLit&>(e).text << "'";
        break;
    case ast::NodeKind::BoolLit:
        os << (static_cast<const ast::BoolLit&>(e).value ? "true" : "false");
        break;
    case ast::NodeKind::IdentExpr:
        os << static_cast<const ast::IdentExpr&>(e).name;
        break;
    case ast::NodeKind::SelfExpr:
        os << "(*this)";
        break;
    case ast::NodeKind::ParenExpr:
        os << "(";
        emit_expr(os, *static_cast<const ast::ParenExpr&>(e).inner);
        os << ")";
        break;
    case ast::NodeKind::UnaryExpr: {
        const auto& u = static_cast<const ast::UnaryExpr&>(e);
        os << unop_text(u.op);
        emit_expr(os, *u.operand);
        break;
    }
    case ast::NodeKind::BinaryExpr: {
        const auto& b = static_cast<const ast::BinaryExpr&>(e);
        emit_expr(os, *b.lhs);
        os << " " << binop_text(b.op) << " ";
        emit_expr(os, *b.rhs);
        break;
    }
    case ast::NodeKind::CallExpr: {
        const auto& c = static_cast<const ast::CallExpr&>(e);
        // Struct construction: if sema typed the call expression as a struct
        // nominal, emit a C++ designated-initializer instead of a function call.
        if (resolution_ != nullptr) {
            auto t = resolution_->type_of(&e);
            if (t != nullptr && t->kind() == sema::TypeKind::Struct
                && t->nominal_decl() != nullptr) {
                const auto& s_decl = static_cast<const ast::StructDecl&>(*t->nominal_decl());
                os << s_decl.name << "{";
                for (std::size_t i = 0; i < c.args.size(); ++i) {
                    if (i != 0) {
                        os << ", ";
                    }
                    if (!c.args[i].label.empty()) {
                        os << "." << c.args[i].label << " = ";
                    }
                    emit_expr(os, *c.args[i].value);
                }
                os << "}";
                break;
            }
        }
        emit_expr(os, *c.callee);
        os << "(";
        for (std::size_t i = 0; i < c.args.size(); ++i) {
            if (i != 0) {
                os << ", ";
            }
            emit_expr(os, *c.args[i].value);
        }
        os << ")";
        break;
    }
    case ast::NodeKind::MemberExpr: {
        const auto& m = static_cast<const ast::MemberExpr&>(e);
        // If the base is an identifier the resolver bound to an Enum decl,
        // this is a static enum case access (`Color.red`) — emit `Color::red`.
        if (resolution_ != nullptr && m.base->kind == ast::NodeKind::IdentExpr) {
            const auto* base_sym = resolution_->symbol_of(m.base.get());
            if (base_sym != nullptr && base_sym->kind == sema::SymbolKind::Enum
                && base_sym->decl != nullptr) {
                const auto& enum_decl = static_cast<const ast::EnumDecl&>(*base_sym->decl);
                os << enum_decl.name << "::" << m.member;
                break;
            }
        }
        emit_expr(os, *m.base);
        os << "." << m.member;
        break;
    }
    case ast::NodeKind::LeadingDotExpr: {
        const auto& d = static_cast<const ast::LeadingDotExpr&>(e);
        // `.red` — resolved by the sema layer; its expression-type is the
        // enum. We need the enum's name to emit `Enum::red`.
        if (resolution_ != nullptr) {
            auto t = resolution_->type_of(&e);
            if (t != nullptr && t->kind() == sema::TypeKind::Enum && t->nominal_decl() != nullptr) {
                const auto& enum_decl = static_cast<const ast::EnumDecl&>(*t->nominal_decl());
                os << enum_decl.name << "::" << d.name;
                break;
            }
        }
        unsupported(os, "leading-dot expression without resolved context", e.range);
        break;
    }
    case ast::NodeKind::MatchExpr:
        emit_match(os, static_cast<const ast::MatchExpr&>(e));
        break;
    case ast::NodeKind::IfExpr: {
        const auto& i = static_cast<const ast::IfExpr&>(e);
        // We can't always lower if-expressions; this works for a statement
        // context but produces invalid code when used in expression position.
        // A future pass should hoist into a temporary + statement.
        os << "([&]{ if (";
        emit_expr(os, *i.cond);
        os << ") { return ";
        emit_expr(os, *i.then_branch);
        os << "; } else { return ";
        if (i.else_branch) {
            emit_expr(os, *i.else_branch);
        } else {
            os << "decltype(";
            emit_expr(os, *i.then_branch);
            os << "){}";
        }
        os << "; } }())";
        break;
    }
    case ast::NodeKind::BlockExpr: {
        // Treat a block expression as an IIFE returning its last statement.
        const auto& b = static_cast<const ast::BlockExpr&>(e);
        os << "[&]{ ";
        for (std::size_t i = 0; i < b.stmts.size(); ++i) {
            const auto& s = *b.stmts[i];
            bool last = (i + 1 == b.stmts.size());
            if (last && s.kind == ast::NodeKind::ExprStmt) {
                os << "return ";
                emit_expr(os, *static_cast<const ast::ExprStmt&>(s).expr);
                os << ";";
            } else {
                std::ostringstream tmp;
                emit_stmt(tmp, s, 0);
                os << tmp.str();
            }
        }
        os << " }()";
        break;
    }
    default:
        unsupported(os, "expression", e.range);
        break;
    }
}

void CppEmitter::emit_type(std::ostream& os, const ast::Type& t) {
    switch (t.kind) {
    case ast::NodeKind::NamedType: {
        const auto& n = static_cast<const ast::NamedType&>(t);
        if (n.path.size() == 1) {
            const auto& m = primitive_map();
            auto it = m.find(n.path[0]);
            if (it != m.end()) {
                os << it->second;
                return;
            }
        }
        for (std::size_t i = 0; i < n.path.size(); ++i) {
            if (i != 0) {
                os << "::";
            }
            os << n.path[i];
        }
        if (n.has_generics) {
            os << "<";
            bool first = true;
            for (const auto& ta : n.type_args) {
                if (!first) {
                    os << ", ";
                }
                first = false;
                emit_type(os, *ta);
            }
            for (auto ci : n.const_args) {
                if (!first) {
                    os << ", ";
                }
                first = false;
                os << ci;
            }
            os << ">";
        }
        break;
    }
    case ast::NodeKind::OptionalType:
        os << "std::optional<";
        emit_type(os, *static_cast<const ast::OptionalType&>(t).inner);
        os << ">";
        break;
    case ast::NodeKind::VectorType: {
        const auto& v = static_cast<const ast::VectorType&>(t);
        os << "std::array<";
        if (v.element) {
            emit_type(os, *v.element);
        } else {
            os << "void";
        }
        os << ", " << v.length << ">";
        break;
    }
    default:
        os << "/*type*/auto";
        break;
    }
}

// ============================================================================
// match — bare enums lower to a switch over the matching enum class.
// ============================================================================

void CppEmitter::emit_match(std::ostream& os, const ast::MatchExpr& m) {
    // We need sema's findings to know what the scrutinee is. Without them we
    // can't tell which `Enum::case` to write per arm.
    if (resolution_ == nullptr) {
        unsupported(os, "match expression without resolved scrutinee", m.range);
        return;
    }
    auto scrutinee_type = resolution_->type_of(m.scrutinee.get());
    if (scrutinee_type == nullptr || scrutinee_type->kind() != sema::TypeKind::Enum
        || scrutinee_type->nominal_decl() == nullptr) {
        unsupported(os, "match over non-enum scrutinee", m.range);
        return;
    }
    const auto& enum_decl = static_cast<const ast::EnumDecl&>(*scrutinee_type->nominal_decl());

    // A payloaded enum lowers to std::visit — out of scope for now.
    for (const auto& c : enum_decl.cases) {
        if (!c.payload.empty()) {
            unsupported(os, "match over payloaded enum", m.range);
            return;
        }
    }

    // Lower the whole expression as an IIFE returning a switch's value through
    // a tail `return`.
    os << "[&]{ switch (";
    emit_expr(os, *m.scrutinee);
    os << ") {\n";
    for (const auto& arm : m.arms) {
        if (arm.is_default) {
            os << "        default: return ";
        } else if (arm.pattern != nullptr && arm.pattern->kind == ast::NodeKind::EnumPat) {
            const auto& ep = static_cast<const ast::EnumPat&>(*arm.pattern);
            os << "        case " << enum_decl.name << "::" << ep.case_name << ": return ";
        } else {
            unsupported(os, "match arm pattern", m.range);
            os << ";\n";
            continue;
        }
        emit_expr(os, *arm.body);
        os << ";\n";
    }
    os << "    } }()";
}

}  // namespace vestra::codegen
