// SPDX-License-Identifier: BSD-2-Clause
// Copyright (c) 2026 James Kane

#include "vestra/codegen/cpp_emitter.hpp"

#include <format>
#include <ostream>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_map>

namespace vestra::codegen {

namespace {

void write_indent(std::ostream& os, int indent) {
    for (int i = 0; i < indent; ++i) {
        os << "    ";
    }
}

// Any payload at all on any case means the enum lowers to a
// `std::variant<case_t…>` wrapper, and every case construction needs
// the `Enum{Enum::case_t{…}}` brace-shape. A bare enum lowers to plain
// `enum class Enum { … }` and constructs as `Enum::case` directly.
bool enum_is_sum_type(const ast::EnumDecl& e) noexcept {
    for (const auto& c : e.cases) {
        if (!c.payload.empty()) {
            return true;
        }
    }
    return false;
}

// Map Vestra primitive names to C++ equivalents.
const std::unordered_map<std::string, std::string>& primitive_map() {
    static const std::unordered_map<std::string, std::string> m = {
        {"Int8", "std::int8_t"},
        {"Int16", "std::int16_t"},
        {"Int32", "std::int32_t"},
        {"Int64", "std::int64_t"},
        {"UInt8", "std::uint8_t"},
        {"UInt16", "std::uint16_t"},
        {"UInt32", "std::uint32_t"},
        {"UInt64", "std::uint64_t"},
        {"Int", "std::intptr_t"},
        {"UInt", "std::uintptr_t"},
        {"Float32", "float"},
        {"Float64", "double"},
        {"Bool", "bool"},
        {"Char", "char32_t"},
        {"Unit", "void"},
        {"String", "std::string"},
        {"Str", "std::string_view"},
        {"StrConst", "std::string_view"},
    };
    return m;
}

}  // namespace

// ----------------------------------------------------------------------------

EmittedUnit CppEmitter::emit(const ast::CompilationUnit& unit, std::string_view output_basename) {
    std::ostringstream hdr;
    std::ostringstream src;

    // §12.3 derive index: collect every `derive(P1, P2, …) for T` at
    // the top level into target-name → {protocol names}. emit_struct
    // and emit_enum read this when injecting the reflective defaults.
    // Each target/protocol path is reduced to its last segment (its
    // simple name) which matches the scope's nominal lookup today.
    derives_by_target_.clear();
    for (const auto& d : unit.decls) {
        if (d->kind != ast::NodeKind::Derive) {
            continue;
        }
        const auto& dd = static_cast<const ast::DeriveDecl&>(*d);
        if (dd.target == nullptr || dd.target->kind != ast::NodeKind::NamedType) {
            continue;
        }
        const auto& tt = static_cast<const ast::NamedType&>(*dd.target);
        if (tt.path.empty()) {
            continue;
        }
        const auto& target_name = tt.path.back();
        for (const auto& p : dd.protocols) {
            if (p == nullptr || p->kind != ast::NodeKind::NamedType) {
                continue;
            }
            const auto& pt = static_cast<const ast::NamedType&>(*p);
            if (pt.path.empty()) {
                continue;
            }
            derives_by_target_[target_name].insert(pt.path.back());
        }
    }

    auto guard = std::string{output_basename};
    for (auto& c : guard) {
        c = (std::isalnum(static_cast<unsigned char>(c)) != 0)
                ? static_cast<char>(std::toupper(static_cast<unsigned char>(c)))
                : '_';
    }

    hdr << "// Generated by vestra-transpiler. Do not edit.\n";
    hdr << "#pragma once\n\n";
    hdr << "#include <cstdint>\n";
    hdr << "#include <format>\n";  // §4 interpolated strings lower to std::format
    hdr << "#include <string>\n";
    hdr << "#include <string_view>\n";
    hdr << "#include <type_traits>\n";  // match-over-payloaded-enum constexpr-if
    hdr << "#include <utility>\n";      // std::move at sink call sites
    hdr << "#include <variant>\n";
    hdr << "#include <vector>\n\n";

    if (unit.module) {
        // Vestra module path → C++ nested namespace.
        hdr << "namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                hdr << "::";
            }
            hdr << unit.module->path[i];
        }
        hdr << " {\n\n";
    }

    src << "// Generated by vestra-transpiler. Do not edit.\n";
    src << "#include \"" << output_basename << ".hpp\"\n\n";

    if (unit.module) {
        src << "namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                src << "::";
            }
            src << unit.module->path[i];
        }
        src << " {\n\n";
    }

    for (const auto& d : unit.decls) {
        // §12.6: skip @when-gated-out decls. The Resolver populated the
        // Resolution's gated set during its own pass.
        if (resolution_ != nullptr && resolution_->is_gated_out(d.get())) {
            continue;
        }
        emit_decl(hdr, src, *d);
    }

    if (unit.module) {
        hdr << "\n}  // namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                hdr << "::";
            }
            hdr << unit.module->path[i];
        }
        hdr << "\n";
        src << "\n}  // namespace ";
        for (std::size_t i = 0; i < unit.module->path.size(); ++i) {
            if (i != 0) {
                src << "::";
            }
            src << unit.module->path[i];
        }
        src << "\n";
    }

    return {hdr.str(), src.str()};
}

// ----------------------------------------------------------------------------

void CppEmitter::unsupported(std::ostream& os, std::string_view what, diag::SourceRange r) {
    reporter_->report(
        diag::Diagnostic::warning(std::format("codegen does not yet support: {}", what)).at(r));
    os << "/* unsupported: " << what << " */";
}

const char* CppEmitter::binop_text(ast::BinaryOp op) {
    switch (op) {
    case ast::BinaryOp::Add:
        return "+";
    case ast::BinaryOp::Sub:
        return "-";
    case ast::BinaryOp::Mul:
        return "*";
    case ast::BinaryOp::Div:
        return "/";
    case ast::BinaryOp::Mod:
        return "%";
    case ast::BinaryOp::Shl:
        return "<<";
    case ast::BinaryOp::Shr:
        return ">>";
    case ast::BinaryOp::BitAnd:
        return "&";
    case ast::BinaryOp::BitOr:
        return "|";
    case ast::BinaryOp::BitXor:
        return "^";
    case ast::BinaryOp::Eq:
        return "==";
    case ast::BinaryOp::Ne:
        return "!=";
    case ast::BinaryOp::Lt:
        return "<";
    case ast::BinaryOp::Le:
        return "<=";
    case ast::BinaryOp::Gt:
        return ">";
    case ast::BinaryOp::Ge:
        return ">=";
    case ast::BinaryOp::And:
        return "&&";
    case ast::BinaryOp::Or:
        return "||";
    case ast::BinaryOp::WrappingAdd:
        return "+";  // C++ on unsigned wraps; signed UB — TODO
    case ast::BinaryOp::WrappingSub:
        return "-";
    case ast::BinaryOp::WrappingMul:
        return "*";
    default:
        return "/*?op*/";
    }
}

const char* CppEmitter::unop_text(ast::UnaryOp op) {
    switch (op) {
    case ast::UnaryOp::Neg:
        return "-";
    case ast::UnaryOp::Not:
        return "!";
    case ast::UnaryOp::BitNot:
        return "~";
    }
    return "?";
}

// ----------------------------------------------------------------------------

void CppEmitter::emit_decl(std::ostream& hdr, std::ostream& src, const ast::Decl& d) {
    switch (d.kind) {
    case ast::NodeKind::Func: {
        const auto& f = static_cast<const ast::FuncDecl&>(d);
        // §12.4 / §12.1: `comptime func`s are evaluated by the folder at
        // compile time only. They have no runtime form to emit (and their
        // bodies often use language constructs — Range, comptime stdlib
        // calls — that don't have a runtime lowering yet). Callers that
        // reach a comptime func via fold get the literal substituted; any
        // hypothetical runtime call sites would be the resolver's job to
        // reject.
        if (f.is_comptime) {
            break;
        }
        emit_func(hdr, src, f);
        break;
    }
    case ast::NodeKind::Struct:
        emit_struct(hdr, static_cast<const ast::StructDecl&>(d));
        break;
    case ast::NodeKind::Enum:
        emit_enum(hdr, static_cast<const ast::EnumDecl&>(d));
        break;
    case ast::NodeKind::Const: {
        const auto& c = static_cast<const ast::ConstDecl&>(d);
        hdr << "inline constexpr ";
        if (c.type) {
            emit_type(hdr, *c.type);
        } else {
            hdr << "auto";
        }
        hdr << " " << c.name << " = ";
        if (c.value) {
            emit_expr(hdr, *c.value);
        }
        hdr << ";\n";
        break;
    }
    case ast::NodeKind::Opaque: {
        const auto& o = static_cast<const ast::OpaqueDecl&>(d);
        hdr << "// opaque type " << o.name << "\n";
        hdr << "enum class " << o.name << " : ";
        emit_type(hdr, *o.underlying);
        hdr << " {};\n";
        break;
    }
    case ast::NodeKind::Derive:
        // §12.3: derive(...) is sugar for an empty extension that
        // adopts the protocol's reflective default. The actual code
        // gets emitted into the target struct/enum body via the
        // derives_by_target_ index built in emit(); there's nothing
        // to write at the DeriveDecl's own position.
        break;
    default:
        unsupported(hdr, std::format("top-level decl kind {}", static_cast<int>(d.kind)), d.range);
        hdr << "\n";
        break;
    }
}

void CppEmitter::emit_func(std::ostream& hdr, std::ostream& src, const ast::FuncDecl& f) {
    // §7 generics: a Vestra generic function lowers to a C++ template. The
    // host compiler then monomorphizes per instantiation, which is what
    // Vestra semantically requires anyway. Const generics ([const N: Int])
    // are deferred — phase 1 only handles type parameters.
    bool has_type_generics = false;
    for (const auto& g : f.generics) {
        if (!g.is_const && !g.name.empty()) {
            has_type_generics = true;
            break;
        }
    }
    auto emit_template_prefix = [&](std::ostream& os) {
        if (!has_type_generics) {
            return;
        }
        os << "template <";
        bool first = true;
        for (const auto& g : f.generics) {
            if (g.is_const || g.name.empty()) {
                continue;
            }
            if (!first) {
                os << ", ";
            }
            first = false;
            os << "class " << g.name;
        }
        os << ">\n";
    };

    auto emit_signature = [&](std::ostream& os) {
        if (f.result) {
            emit_type(os, *f.result);
        } else {
            os << "void";
        }
        os << " " << f.name << "(";
        for (std::size_t i = 0; i < f.params.size(); ++i) {
            if (i != 0) {
                os << ", ";
            }
            const auto& p = f.params[i];
            // Mode mapping (very rough first pass — §5 ownership is unresolved):
            //   read  → const T&
            //   inout → T&
            //   sink  → T&&
            switch (p.mode) {
            case ast::ParamMode::Read:
                os << "const ";
                if (p.type) {
                    emit_type(os, *p.type);
                }
                os << "& " << p.name;
                break;
            case ast::ParamMode::Inout:
                if (p.type) {
                    emit_type(os, *p.type);
                }
                os << "& " << p.name;
                break;
            case ast::ParamMode::Sink:
                if (p.type) {
                    emit_type(os, *p.type);
                }
                os << "&& " << p.name;
                break;
            }
        }
        os << ")";
    };

    // Templates must be visible at every instantiation site, so a generic
    // function lives entirely in the header. Non-generics keep the
    // declaration/definition split.
    if (has_type_generics) {
        emit_template_prefix(hdr);
        hdr << "[[nodiscard]] ";
        emit_signature(hdr);
        if (!f.body) {
            hdr << ";\n";
            return;
        }
        hdr << " {\n";
        if (f.body->kind == ast::NodeKind::BlockExpr) {
            const auto& blk = static_cast<const ast::BlockExpr&>(*f.body);
            for (const auto& s : blk.stmts) {
                emit_stmt(hdr, *s, 1);
            }
        } else {
            unsupported(hdr, "non-block function body", f.body->range);
        }
        hdr << "}\n\n";
        return;
    }

    hdr << "[[nodiscard]] ";
    emit_signature(hdr);
    hdr << ";\n";

    if (!f.body) {
        return;
    }

    emit_signature(src);
    src << " {\n";
    if (f.body->kind == ast::NodeKind::BlockExpr) {
        const auto& blk = static_cast<const ast::BlockExpr&>(*f.body);
        for (const auto& s : blk.stmts) {
            emit_stmt(src, *s, 1);
        }
    } else {
        unsupported(src, "non-block function body", f.body->range);
    }
    src << "}\n\n";
}

void CppEmitter::emit_struct(std::ostream& hdr, const ast::StructDecl& s) {
    hdr << "struct " << s.name << " {\n";
    for (const auto& f : s.fields) {
        write_indent(hdr, 1);
        if (f.type) {
            emit_type(hdr, *f.type);
        }
        hdr << " " << f.name << "{};\n";
    }
    // §12.3 derive(Eq): a defaulted operator== gives us field-by-field
    // structural equality for free, with the C++ compiler doing the
    // recursion through any nested derived-Eq members. Bigger derives
    // (Hash, Clone) ride on the same index in later phases.
    if (auto it = derives_by_target_.find(s.name); it != derives_by_target_.end()) {
        if (it->second.contains("Eq")) {
            write_indent(hdr, 1);
            hdr << "[[nodiscard]] bool operator==(const " << s.name
                << "&) const noexcept = default;\n";
        }
    }
    hdr << "};\n\n";
}

void CppEmitter::emit_enum(std::ostream& hdr, const ast::EnumDecl& e) {
    // A Vestra enum with payloads maps cleanly to std::variant; bare enums to
    // a C++ enum class. We detect "all bare" cheaply.
    bool all_bare = true;
    for (const auto& c : e.cases) {
        if (!c.payload.empty()) {
            all_bare = false;
            break;
        }
    }
    if (all_bare) {
        hdr << "enum class " << e.name << " {\n";
        for (const auto& c : e.cases) {
            write_indent(hdr, 1);
            hdr << c.name << ",\n";
        }
        hdr << "};\n\n";
        // C++ `enum class` already has operator== built in, so
        // derive(Eq) for a bare enum needs no extra code — but flag
        // any other (unsupported-for-bare) derives as TODO.
        return;
    }
    // Sum type — emit a struct-of-variant. TODO: tighter sum-type lowering.
    //
    // Detect derive(Eq) up front: `std::variant::operator==` requires
    // each alternative to be equality-comparable, so we need to add a
    // defaulted operator== to every case_t too (cheap — it's all POD
    // member compares).
    const bool wants_eq =
        derives_by_target_.contains(e.name) && derives_by_target_.at(e.name).contains("Eq");
    hdr << "struct " << e.name << " {\n";
    for (const auto& c : e.cases) {
        write_indent(hdr, 1);
        hdr << "struct " << c.name << "_t {";
        for (std::size_t i = 0; i < c.payload.size(); ++i) {
            if (i != 0) {
                hdr << " ";
            }
            if (c.payload[i].second) {
                emit_type(hdr, *c.payload[i].second);
            }
            hdr << " " << (c.payload[i].first.empty() ? std::format("_{}", i) : c.payload[i].first)
                << "{}; ";
        }
        if (wants_eq) {
            hdr << "[[nodiscard]] bool operator==(const " << c.name
                << "_t&) const noexcept = default; ";
        }
        hdr << "};\n";
    }
    write_indent(hdr, 1);
    hdr << "std::variant<";
    for (std::size_t i = 0; i < e.cases.size(); ++i) {
        if (i != 0) {
            hdr << ", ";
        }
        hdr << e.cases[i].name << "_t";
    }
    hdr << "> value{};\n";
    // §12.3 derive(Eq): sum-type wrappers need a defaulted operator==
    // too; std::variant compares structurally provided every alternative
    // is comparable, and the defaulted operator delegates accordingly.
    if (auto it = derives_by_target_.find(e.name); it != derives_by_target_.end()) {
        if (it->second.contains("Eq")) {
            write_indent(hdr, 1);
            hdr << "[[nodiscard]] bool operator==(const " << e.name
                << "&) const noexcept = default;\n";
        }
    }
    hdr << "};\n\n";
}

void CppEmitter::emit_block(std::ostream& os, const ast::BlockExpr& b, int indent) {
    os << "{\n";
    for (const auto& s : b.stmts) {
        emit_stmt(os, *s, indent + 1);
    }
    write_indent(os, indent);
    os << "}";
}

void CppEmitter::emit_stmt(std::ostream& os, const ast::Stmt& s, int indent) {
    write_indent(os, indent);
    switch (s.kind) {
    case ast::NodeKind::LetStmt: {
        const auto& l = static_cast<const ast::LetStmt&>(s);
        // Vestra's `let` is "no reassignment" — but it does allow consumption
        // (move). C++'s `const` is stricter (no rebind AND no move-from), so
        // we use plain `auto` / `T` here. Sema rejects assignment to `let`
        // bindings, which is the part C++'s const was buying us.
        if (l.type) {
            emit_type(os, *l.type);
            os << " ";
        } else {
            os << "auto ";
        }
        if (l.pattern && l.pattern->kind == ast::NodeKind::IdentPat) {
            os << static_cast<const ast::IdentPat&>(*l.pattern).name;
        } else if (l.pattern && l.pattern->kind == ast::NodeKind::BindPat) {
            os << static_cast<const ast::BindPat&>(*l.pattern).name;
        } else {
            os << "_bind";
        }
        os << " = ";
        if (l.value) {
            emit_expr(os, *l.value);
        }
        os << ";\n";
        break;
    }
    case ast::NodeKind::VarStmt: {
        const auto& v = static_cast<const ast::VarStmt&>(s);
        if (v.type) {
            emit_type(os, *v.type);
            os << " ";
        } else {
            os << "auto ";
        }
        if (v.pattern && v.pattern->kind == ast::NodeKind::IdentPat) {
            os << static_cast<const ast::IdentPat&>(*v.pattern).name;
        } else if (v.pattern && v.pattern->kind == ast::NodeKind::BindPat) {
            os << static_cast<const ast::BindPat&>(*v.pattern).name;
        } else {
            os << "_bind";
        }
        os << " = ";
        if (v.value) {
            emit_expr(os, *v.value);
        }
        os << ";\n";
        break;
    }
    case ast::NodeKind::ExprStmt:
        emit_expr(os, *static_cast<const ast::ExprStmt&>(s).expr);
        os << ";\n";
        break;
    case ast::NodeKind::ReturnStmt: {
        const auto& r = static_cast<const ast::ReturnStmt&>(s);
        // Special-case `return if cond { a } else { b }`: emit a direct
        // if/return pair rather than the IIFE-wrapped lambda we use for
        // if-expressions in arbitrary positions. The IIFE form forces the
        // compiler to deduce a single return type from both branches,
        // which fails when one branch is a literal (int) and the other is
        // a Vestra Int value (intptr_t). Lowering as two `return` paths
        // lets the surrounding function's return type pin both branches.
        if (r.value && r.value->kind == ast::NodeKind::IfExpr) {
            const auto& i = static_cast<const ast::IfExpr&>(*r.value);
            os << "if (";
            emit_expr(os, *i.cond);
            os << ") { return ";
            emit_expr(os, *i.then_branch);
            os << "; }";
            if (i.else_branch) {
                os << " else { return ";
                emit_expr(os, *i.else_branch);
                os << "; }";
            }
            os << "\n";
            break;
        }
        os << "return";
        if (r.value) {
            os << " ";
            emit_expr(os, *r.value);
        }
        os << ";\n";
        break;
    }
    case ast::NodeKind::BreakStmt:
        os << "break;\n";
        break;
    case ast::NodeKind::ContinueStmt:
        os << "continue;\n";
        break;
    case ast::NodeKind::AssignStmt: {
        const auto& a = static_cast<const ast::AssignStmt&>(s);
        emit_expr(os, *a.target);
        switch (a.op) {
        case ast::AssignOp::Assign:
            os << " = ";
            break;
        case ast::AssignOp::AddAssign:
            os << " += ";
            break;
        case ast::AssignOp::SubAssign:
            os << " -= ";
            break;
        case ast::AssignOp::MulAssign:
            os << " *= ";
            break;
        case ast::AssignOp::DivAssign:
            os << " /= ";
            break;
        case ast::AssignOp::ModAssign:
            os << " %= ";
            break;
        case ast::AssignOp::BitAndAssign:
            os << " &= ";
            break;
        case ast::AssignOp::BitOrAssign:
            os << " |= ";
            break;
        case ast::AssignOp::BitXorAssign:
            os << " ^= ";
            break;
        case ast::AssignOp::ShlAssign:
            os << " <<= ";
            break;
        case ast::AssignOp::ShrAssign:
            os << " >>= ";
            break;
        }
        emit_expr(os, *a.value);
        os << ";\n";
        break;
    }
    case ast::NodeKind::WhileStmt: {
        const auto& w = static_cast<const ast::WhileStmt&>(s);
        os << "while (";
        emit_expr(os, *w.cond);
        os << ") ";
        if (w.body && w.body->kind == ast::NodeKind::BlockExpr) {
            emit_block(os, static_cast<const ast::BlockExpr&>(*w.body), indent);
            os << "\n";
        } else {
            os << "{}\n";
        }
        break;
    }
    case ast::NodeKind::ForStmt: {
        const auto& f = static_cast<const ast::ForStmt&>(s);
        os << "for (const auto& ";
        if (f.pattern && f.pattern->kind == ast::NodeKind::IdentPat) {
            os << static_cast<const ast::IdentPat&>(*f.pattern).name;
        } else if (f.pattern && f.pattern->kind == ast::NodeKind::BindPat) {
            os << static_cast<const ast::BindPat&>(*f.pattern).name;
        } else {
            os << "_it";
        }
        os << " : ";
        emit_expr(os, *f.iter);
        os << ") ";
        if (f.body && f.body->kind == ast::NodeKind::BlockExpr) {
            emit_block(os, static_cast<const ast::BlockExpr&>(*f.body), indent);
            os << "\n";
        } else {
            os << "{}\n";
        }
        break;
    }
    default:
        unsupported(os, "stmt", s.range);
        os << "\n";
        break;
    }
}

void CppEmitter::emit_expr(std::ostream& os, const ast::Expr& e) {
    // §12.1 folded literal short-circuit: when sema's comptime folder
    // computed a constant value for this expression, emit that value
    // directly. Skips the whole structure (e.g. `1 << 8 - 1` becomes
    // `255` in the output) while still giving the C++ compiler an
    // exact-width literal.
    if (resolution_ != nullptr) {
        if (const auto* v = resolution_->folded_value(&e)) {
            os << v->to_cpp_literal();
            return;
        }
    }
    switch (e.kind) {
    case ast::NodeKind::IntLit:
        os << static_cast<const ast::IntLit&>(e).text;
        break;
    case ast::NodeKind::FloatLit:
        os << static_cast<const ast::FloatLit&>(e).text;
        break;
    case ast::NodeKind::StringLit:
        os << "std::string_view(\"" << static_cast<const ast::StringLit&>(e).text << "\")";
        break;
    case ast::NodeKind::InterpStringExpr: {
        // §4 lowering: each literal fragment contributes a `{{...}}`-free
        // chunk to the format string, each splice contributes `{}` plus
        // an argument. std::format does the per-type rendering at
        // runtime; for now we trust Display ≈ std::formatter, which
        // works out of the box for the numeric / Bool / string-like
        // primitives. The result is a freshly-allocated std::string,
        // matching §4's "interpolation is an allocation."
        const auto& is_ = static_cast<const ast::InterpStringExpr&>(e);
        os << "std::format(\"";
        for (const auto& seg : is_.segments) {
            if (seg.expr == nullptr) {
                // Literal fragment: escape `{` and `}` for std::format.
                for (char c : seg.literal) {
                    if (c == '{' || c == '}') {
                        os << c << c;
                    } else {
                        os << c;
                    }
                }
            } else {
                os << "{}";
            }
        }
        os << "\"";
        for (const auto& seg : is_.segments) {
            if (seg.expr != nullptr) {
                os << ", ";
                emit_expr(os, *seg.expr);
            }
        }
        os << ")";
        break;
    }
    case ast::NodeKind::CharLit:
        os << "U'" << static_cast<const ast::CharLit&>(e).text << "'";
        break;
    case ast::NodeKind::BoolLit:
        os << (static_cast<const ast::BoolLit&>(e).value ? "true" : "false");
        break;
    case ast::NodeKind::IdentExpr:
        os << static_cast<const ast::IdentExpr&>(e).name;
        break;
    case ast::NodeKind::SelfExpr:
        os << "(*this)";
        break;
    case ast::NodeKind::ParenExpr:
        os << "(";
        emit_expr(os, *static_cast<const ast::ParenExpr&>(e).inner);
        os << ")";
        break;
    case ast::NodeKind::UnaryExpr: {
        const auto& u = static_cast<const ast::UnaryExpr&>(e);
        os << unop_text(u.op);
        emit_expr(os, *u.operand);
        break;
    }
    case ast::NodeKind::BinaryExpr: {
        const auto& b = static_cast<const ast::BinaryExpr&>(e);
        emit_expr(os, *b.lhs);
        os << " " << binop_text(b.op) << " ";
        emit_expr(os, *b.rhs);
        break;
    }
    case ast::NodeKind::CallExpr: {
        const auto& c = static_cast<const ast::CallExpr&>(e);
        // Payloaded-enum case construction: `Shape.circle(radius: 1.0)` →
        // `Shape{Shape::circle_t{1.0}}`. Bare cases on a payloaded enum
        // come through the MemberExpr path above; here we handle the
        // call form so the args slot into the right `case_t` aggregate.
        if (resolution_ != nullptr && c.callee->kind == ast::NodeKind::MemberExpr) {
            const auto& mem = static_cast<const ast::MemberExpr&>(*c.callee);
            if (mem.base->kind == ast::NodeKind::IdentExpr) {
                if (const auto* sym = resolution_->symbol_of(mem.base.get())) {
                    if (sym->kind == sema::SymbolKind::Enum && sym->decl != nullptr) {
                        const auto& ed = static_cast<const ast::EnumDecl&>(*sym->decl);
                        if (enum_is_sum_type(ed)) {
                            os << ed.name << "{" << ed.name << "::" << mem.member << "_t{";
                            for (std::size_t i = 0; i < c.args.size(); ++i) {
                                if (i != 0) {
                                    os << ", ";
                                }
                                emit_expr(os, *c.args[i].value);
                            }
                            os << "}}";
                            break;
                        }
                    }
                }
            }
        }
        // §17.x conversion-call lowering: `Float64(i)` → `static_cast<double>(i)`.
        // Sema accepts a bare numeric-primitive ident in callee position and
        // produces a one-arg call typed at that primitive; here we map it to
        // a C++ static_cast against the same primitive's C++ name from the
        // shared primitive_map().
        if (c.callee->kind == ast::NodeKind::IdentExpr && c.args.size() == 1) {
            const auto& callee_ident = static_cast<const ast::IdentExpr&>(*c.callee);
            const auto& m = primitive_map();
            if (auto it = m.find(callee_ident.name);
                it != m.end() && it->first != "Bool" && it->first != "Char" && it->first != "Unit"
                && it->first != "String" && it->first != "Str" && it->first != "StrConst") {
                os << "static_cast<" << it->second << ">(";
                emit_expr(os, *c.args[0].value);
                os << ")";
                break;
            }
        }
        // Struct construction: if sema typed the call expression as a struct
        // nominal, emit a C++ designated-initializer instead of a function call.
        if (resolution_ != nullptr) {
            auto t = resolution_->type_of(&e);
            if (t != nullptr && t->kind() == sema::TypeKind::Struct
                && t->nominal_decl() != nullptr) {
                const auto& s_decl = static_cast<const ast::StructDecl&>(*t->nominal_decl());
                os << s_decl.name << "{";
                for (std::size_t i = 0; i < c.args.size(); ++i) {
                    if (i != 0) {
                        os << ", ";
                    }
                    if (!c.args[i].label.empty()) {
                        os << "." << c.args[i].label << " = ";
                    }
                    emit_expr(os, *c.args[i].value);
                }
                os << "}";
                break;
            }
        }
        // Recover the callee's parameter modes so we can wrap sink arguments
        // in std::move(). If the callee resolves to a Vestra func declaration,
        // use its params; otherwise treat every param as `read` (the default).
        const ast::FuncDecl* fn = nullptr;
        if (resolution_ != nullptr) {
            const auto* sym = resolution_->symbol_of(c.callee.get());
            if (sym != nullptr && sym->decl != nullptr && sym->decl->kind == ast::NodeKind::Func) {
                fn = static_cast<const ast::FuncDecl*>(sym->decl);
            }
        }
        emit_expr(os, *c.callee);
        os << "(";
        for (std::size_t i = 0; i < c.args.size(); ++i) {
            if (i != 0) {
                os << ", ";
            }
            const bool is_sink = fn != nullptr && i < fn->params.size()
                                 && fn->params[i].mode == ast::ParamMode::Sink;
            // For a sink param, the value must arrive as an rvalue. The
            // simplest correct lowering: always std::move at the call site.
            // (`std::move(temporary)` is harmless — it just stays an rvalue.)
            if (is_sink) {
                os << "std::move(";
            }
            emit_expr(os, *c.args[i].value);
            if (is_sink) {
                os << ")";
            }
        }
        os << ")";
        break;
    }
    case ast::NodeKind::MemberExpr: {
        const auto& m = static_cast<const ast::MemberExpr&>(e);
        // If the base is an identifier the resolver bound to an Enum decl,
        // this is a static enum case access. Bare enums emit as
        // `Color::red`; payloaded enums lower as struct-of-variant so a
        // bare-case access needs the `Shape{Shape::point_t{}}` wrap.
        if (resolution_ != nullptr && m.base->kind == ast::NodeKind::IdentExpr) {
            const auto* base_sym = resolution_->symbol_of(m.base.get());
            if (base_sym != nullptr && base_sym->kind == sema::SymbolKind::Enum
                && base_sym->decl != nullptr) {
                const auto& enum_decl = static_cast<const ast::EnumDecl&>(*base_sym->decl);
                if (enum_is_sum_type(enum_decl)) {
                    os << enum_decl.name << "{" << enum_decl.name << "::" << m.member << "_t{}}";
                } else {
                    os << enum_decl.name << "::" << m.member;
                }
                break;
            }
        }
        emit_expr(os, *m.base);
        os << "." << m.member;
        break;
    }
    case ast::NodeKind::IndexExpr: {
        // C++ subscript is the same shape as Vestra's: `base[i0, i1, ...]`.
        // The Vestra-side type-check already verified the base is indexable
        // (a vector / array / slice); we just pass through.
        const auto& ix = static_cast<const ast::IndexExpr&>(e);
        emit_expr(os, *ix.base);
        os << "[";
        for (std::size_t i = 0; i < ix.indices.size(); ++i) {
            if (i != 0) {
                os << ", ";
            }
            emit_expr(os, *ix.indices[i]);
        }
        os << "]";
        break;
    }
    case ast::NodeKind::LeadingDotExpr: {
        const auto& d = static_cast<const ast::LeadingDotExpr&>(e);
        // `.red` — resolved by the sema layer; its expression-type is the
        // enum. We need the enum's name to emit `Enum::red`.
        if (resolution_ != nullptr) {
            auto t = resolution_->type_of(&e);
            if (t != nullptr && t->kind() == sema::TypeKind::Enum && t->nominal_decl() != nullptr) {
                const auto& enum_decl = static_cast<const ast::EnumDecl&>(*t->nominal_decl());
                os << enum_decl.name << "::" << d.name;
                break;
            }
        }
        unsupported(os, "leading-dot expression without resolved context", e.range);
        break;
    }
    case ast::NodeKind::MatchExpr:
        emit_match(os, static_cast<const ast::MatchExpr&>(e));
        break;
    case ast::NodeKind::IfExpr: {
        const auto& i = static_cast<const ast::IfExpr&>(e);
        // We can't always lower if-expressions; this works for a statement
        // context but produces invalid code when used in expression position.
        // A future pass should hoist into a temporary + statement.
        os << "([&]{ if (";
        emit_expr(os, *i.cond);
        os << ") { return ";
        emit_expr(os, *i.then_branch);
        os << "; } else { return ";
        if (i.else_branch) {
            emit_expr(os, *i.else_branch);
        } else {
            os << "decltype(";
            emit_expr(os, *i.then_branch);
            os << "){}";
        }
        os << "; } }())";
        break;
    }
    case ast::NodeKind::BlockExpr: {
        // Treat a block expression as an IIFE returning its last statement.
        const auto& b = static_cast<const ast::BlockExpr&>(e);
        os << "[&]{ ";
        for (std::size_t i = 0; i < b.stmts.size(); ++i) {
            const auto& s = *b.stmts[i];
            bool last = (i + 1 == b.stmts.size());
            if (last && s.kind == ast::NodeKind::ExprStmt) {
                os << "return ";
                emit_expr(os, *static_cast<const ast::ExprStmt&>(s).expr);
                os << ";";
            } else {
                std::ostringstream tmp;
                emit_stmt(tmp, s, 0);
                os << tmp.str();
            }
        }
        os << " }()";
        break;
    }
    default:
        unsupported(os, "expression", e.range);
        break;
    }
}

void CppEmitter::emit_type(std::ostream& os, const ast::Type& t) {
    switch (t.kind) {
    case ast::NodeKind::NamedType: {
        const auto& n = static_cast<const ast::NamedType&>(t);
        if (n.path.size() == 1) {
            const auto& m = primitive_map();
            auto it = m.find(n.path[0]);
            if (it != m.end()) {
                os << it->second;
                return;
            }
        }
        for (std::size_t i = 0; i < n.path.size(); ++i) {
            if (i != 0) {
                os << "::";
            }
            os << n.path[i];
        }
        if (n.has_generics) {
            os << "<";
            bool first = true;
            for (const auto& ta : n.type_args) {
                if (!first) {
                    os << ", ";
                }
                first = false;
                emit_type(os, *ta);
            }
            for (auto ci : n.const_args) {
                if (!first) {
                    os << ", ";
                }
                first = false;
                os << ci;
            }
            os << ">";
        }
        break;
    }
    case ast::NodeKind::OptionalType:
        os << "std::optional<";
        emit_type(os, *static_cast<const ast::OptionalType&>(t).inner);
        os << ">";
        break;
    case ast::NodeKind::VectorType: {
        const auto& v = static_cast<const ast::VectorType&>(t);
        os << "std::array<";
        if (v.element) {
            emit_type(os, *v.element);
        } else {
            os << "void";
        }
        os << ", " << v.length << ">";
        break;
    }
    default:
        os << "/*type*/auto";
        break;
    }
}

// ============================================================================
// match — bare enums lower to a switch over the matching enum class.
// ============================================================================

void CppEmitter::emit_match(std::ostream& os, const ast::MatchExpr& m) {
    // We need sema's findings to know what the scrutinee is. Without them we
    // can't tell which `Enum::case` to write per arm.
    if (resolution_ == nullptr) {
        unsupported(os, "match expression without resolved scrutinee", m.range);
        return;
    }
    auto scrutinee_type = resolution_->type_of(m.scrutinee.get());
    if (scrutinee_type == nullptr || scrutinee_type->kind() != sema::TypeKind::Enum
        || scrutinee_type->nominal_decl() == nullptr) {
        unsupported(os, "match over non-enum scrutinee", m.range);
        return;
    }
    const auto& enum_decl = static_cast<const ast::EnumDecl&>(*scrutinee_type->nominal_decl());

    // Two lowerings depending on whether any case carries a payload. A
    // bare enum lowers to a plain `switch (e) { case … }` IIFE; a
    // payloaded enum lowers to `std::visit(...)` with a constexpr-if
    // chain dispatching on each alternative's type.
    bool has_payload = false;
    for (const auto& c : enum_decl.cases) {
        if (!c.payload.empty()) {
            has_payload = true;
            break;
        }
    }

    if (!has_payload) {
        // Lower the whole expression as an IIFE returning a switch's value
        // through a tail `return`. Wildcard patterns map to `default:`.
        os << "[&]{ switch (";
        emit_expr(os, *m.scrutinee);
        os << ") {\n";
        for (const auto& arm : m.arms) {
            if (arm.is_default
                || (arm.pattern != nullptr && arm.pattern->kind == ast::NodeKind::WildcardPat)) {
                os << "        default: return ";
            } else if (arm.pattern != nullptr && arm.pattern->kind == ast::NodeKind::EnumPat) {
                const auto& ep = static_cast<const ast::EnumPat&>(*arm.pattern);
                os << "        case " << enum_decl.name << "::" << ep.case_name << ": return ";
            } else {
                unsupported(os, "match arm pattern", m.range);
                os << ";\n";
                continue;
            }
            emit_expr(os, *arm.body);
            os << ";\n";
        }
        os << "    } }()";
        return;
    }

    // Payloaded enum: lower to std::visit with constexpr-if dispatch.
    //
    //   std::visit([&](auto&& __vstr_alt) -> auto {
    //       using __vstr_alt_t = std::decay_t<decltype(__vstr_alt)>;
    //       if constexpr (std::is_same_v<__vstr_alt_t, Enum::case_t>) {
    //           auto&& binding = __vstr_alt.field;   // per BindPat child
    //           return <arm body>;
    //       } else if constexpr (…) { … }
    //       else { return <default body>; }                  // optional
    //       else { std::unreachable(); }                     // safety net
    //   }, scrutinee.value)
    //
    // Sema verifies exhaustiveness so the std::unreachable() arm only
    // exists to satisfy C++'s "all paths must return" rule when there's
    // no user-supplied default.
    os << "std::visit([&](auto&& __vstr_alt) -> auto {\n";
    os << "        using __vstr_alt_t = std::decay_t<decltype(__vstr_alt)>;\n";

    bool first = true;
    const ast::MatchArm* default_arm = nullptr;

    for (const auto& arm : m.arms) {
        if (arm.is_default
            || (arm.pattern != nullptr && arm.pattern->kind == ast::NodeKind::WildcardPat)) {
            default_arm = &arm;
            continue;
        }
        if (arm.pattern == nullptr || arm.pattern->kind != ast::NodeKind::EnumPat) {
            unsupported(os, "match arm pattern over payloaded enum", m.range);
            continue;
        }
        const auto& ep = static_cast<const ast::EnumPat&>(*arm.pattern);

        // Locate the case decl so we can resolve positional vs labeled
        // payload field names (parallels emit_enum's `_{i}` fallback).
        const ast::EnumDecl::Case* case_decl = nullptr;
        for (const auto& c : enum_decl.cases) {
            if (c.name == ep.case_name) {
                case_decl = &c;
                break;
            }
        }
        if (case_decl == nullptr) {
            unsupported(os, "match arm references unknown enum case", arm.pattern->range);
            continue;
        }

        if (first) {
            write_indent(os, 2);
            os << "if";
        } else {
            os << " else if";  // chained — previous arm ended with bare "}"
        }
        os << " constexpr (std::is_same_v<__vstr_alt_t, " << enum_decl.name << "::" << ep.case_name
           << "_t>) {\n";

        for (std::size_t i = 0; i < ep.children.size() && i < case_decl->payload.size(); ++i) {
            const auto& child = *ep.children[i];
            std::string field_name = case_decl->payload[i].first.empty()
                                         ? std::format("_{}", i)
                                         : case_decl->payload[i].first;
            if (child.kind == ast::NodeKind::BindPat) {
                write_indent(os, 3);
                os << "auto&& " << static_cast<const ast::BindPat&>(child).name << " = __vstr_alt."
                   << field_name << ";\n";
            } else if (child.kind == ast::NodeKind::IdentPat) {
                write_indent(os, 3);
                os << "auto&& " << static_cast<const ast::IdentPat&>(child).name << " = __vstr_alt."
                   << field_name << ";\n";
            }
            // Wildcard / nested patterns: nothing to bind. Sub-pattern
            // matching is a follow-on.
        }

        write_indent(os, 3);
        os << "return ";
        emit_expr(os, *arm.body);
        os << ";\n";
        write_indent(os, 2);
        os << "}";
        first = false;
    }

    if (default_arm != nullptr) {
        os << " else {\n";
        write_indent(os, 3);
        os << "return ";
        emit_expr(os, *default_arm->body);
        os << ";\n";
        write_indent(os, 2);
        os << "}";
    } else {
        // Sema's exhaustiveness check should have caught a real miss; this
        // branch only exists to satisfy the C++ compiler's "no return"
        // diagnostic on the lambda.
        os << " else { std::unreachable(); }";
    }
    os << "\n    }, ";
    emit_expr(os, *m.scrutinee);
    os << ".value)";
}

}  // namespace vestra::codegen
